[package]
name = "slint-ui"
version = "0.1.0"
edition = "2021"


[package.metadata.wasm-bindgen.profile.dev]
wasm-opt = false


[lib]
crate-type = ["lib", "cdylib"]


[dependencies]
slint = "1.6.0"
wasm-bindgen = "0.2.92"
